api_version = "2026-07"

[[extensions]]
name = "Checkout Image"
handle = "checkout-image"
uid = "e18a3560-340f-46cc-66c8-cdd71b8378b5ceb3a773"
type = "ui_extension"

[extensions.capabilities]
network_access = true

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/index.js"

[extensions.settings]
[[extensions.settings.fields]]
key = "backend_url"
type = "single_line_text_field"
name = "Backend API URL (e.g. https://checkoutandatc.zoyava.terzettoo.com)"
