api_version = "2026-07"

[extensions.capabilities]
network_access = true

[[extensions]]
name = "Judge.me Reviews & Branding"
handle = "judgeme-reviews-branding"
uid = "a1c2f2b1-698a-022d-f1d8-162cb4e7328998c81da5"
type = "ui_extension"

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/index.js"

[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/index.js"

[[extensions.targeting]]
target = "customer-account.order-status.block.render"
module = "./src/index.js"

[extensions.settings]
[[extensions.settings.fields]]
key = "hide_header"
type = "boolean"
name = "Hide Checkout Header Elements"

[[extensions.settings.fields]]
key = "hide_footer"
type = "boolean"
name = "Hide Checkout Footer Elements"
