api_version = "2026-07"

[[extensions]]
name = "Checkout Timer"
handle = "checkout-timer"
uid = "f5fbef66-9be6-6eb7-5ceb-5784c1ea6116fc6919c5"
type = "ui_extension"

[extensions.capabilities]
network_access = true

[[extensions.targeting]]
target = "purchase.checkout.block.render"
module = "./src/index.js"

[[extensions.targeting]]
target = "purchase.thank-you.block.render"
module = "./src/index.js"

[[extensions.targeting]]
target = "customer-account.order-status.block.render"
module = "./src/index.js"

[extensions.settings]
[[extensions.settings.fields]]
key = "hide_header"
type = "boolean"
name = "Hide Checkout Header Elements"

[[extensions.settings.fields]]
key = "hide_footer"
type = "boolean"
name = "Hide Checkout Footer Elements"

[[extensions.settings.fields]]
key = "backend_url"
type = "single_line_text_field"
name = "Backend API URL (e.g. https://checkoutandatc.zoyava.terzettoo.com)"
